---
title: "Welcome to Target Trial Emulation and Causal Inference Tutorials"
listing:
  contents:
    - "*.qmd"
    - "*.Rmd"
    - "*.html"
  sort: "title"
  type: default
  fields: [title, description, reading-time]
---

## About

R tutorials for implementing target trial emulation (TTE) and causal inference methods to estimate treatment effects using observational data. These tutorials introduce important concepts in TTE and provide step-by-step instructions for deploying the procedures with examples.  

## Start here

- **All tutorials:** See the [tutorials listing](index.html)
- Or jump to: [Preparing Analysis Data by Emulating A Single Target Trial](TTEdemoSig.html)
- Or jump to: [Preparing Analysis Data by Emulating A Sequence of Target Trials](TTEdemoSeq.html)
- Or jump to: [Introduction to Causal Inference and Intention to Treat Analysis](IntentionToTreat.html)
- Or jump to: [Per-protocol Analysis](PerProtocol.html)
- Or jump to: [Doubly Robust Estimation of Average Treatment Effects Using Pseudo Observations](DRpseudo.html)
- Or jump to: [Augmented Inverse Probability Weighted Complete Case Estimator for Survival Outcomes](DRaipwcc.html)
